# -*- coding: utf-8 -*-
"""StockMailing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18XEhyAVWnouxFEPMkJUgwQUUxHsoLA-D
"""

#Para consultar los valores
from bs4 import BeautifulSoup
import requests
#Para los mails
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
import smtplib

def yahoovalues(symbols):
  prices = []
  for i in symbols:
    url = 'https://finance.yahoo.com/quote/' + i
    page = requests.get(url, headers={
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
    })
    soup = BeautifulSoup(page.text, 'html.parser')
    prices.append(soup.find('fin-streamer', {'class': 'Fw(b) Fz(36px) Mb(-4px) D(ib)'}).text)

  #print(price)
  return prices
# thanks: https://stackoverflow.com/questions/70524523/why-is-web-scraping-stock-prices-through-beautiful-soup-returning-a-different-pr

def mymailing(symbols,prices,tolist):
  msg = MIMEMultipart()
  message = 'Hola suscriptor, un poco de info para ti: \n\n'

  for i in symbols:
    message += 'Este es el valor actual de ' + i + ': ' + prices[symbols.index(i)]
    if len(i) == 4:
      message += '$\n\n'
    else:
      message += '€\n\n'

  message += 'Abrazo'
  # setup the parameters of the message
  password = ""                                 #password para la cuenta de correo emisor
  msg['From'] = ""                              #dirección de correo emisor (gmail)
  msg['To'] = ""                                #Dirección qeu aparecerá como receptora en el mensaje, aunqeu el correo llegará a la lista de direcciones de 'tolist'
  #msg['Cc'] = ""
  msg['Subject'] = "Stock Subscription"
  msg.attach(MIMEText(message, 'plain'))

  server = smtplib.SMTP('smtp.gmail.com: 587')

  server.starttls()

  # Login Credentials for sending the mail
  server.login(msg['From'], password)


  # send the message via the server.
  server.sendmail(msg['From'], tolist, msg.as_string())

  server.quit()

  print("Successfully sent email to %s:" % (tolist))

  #Para solucionar problemas de autenticación de la cuenta de correo emisora ver la respuesta 2 de este hilo https://stackoverflow.com/questions/16512592/login-credentials-not-working-with-gmail-smtp

symbols = ['FTNT','IAG.MC']           #Simbolos de valores de los que se quiere obtener el precio (segun aparezcan en yahoo), añadir aquí los que se deseen
prices = yahoovalues(symbols)         #Obtener los precios de los valores deseados
tolist = []                           #lista de mails a los que se queire distribuir la info
mymailing(symbols,prices,tolist)      #confeccion del mensaje con los valores y envío por correo a la lista de distribución